# Generated by Django 4.2 on 2025-03-31 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_key",
                    models.CharField(max_length=50, unique=True, verbose_name="配置键"),
                ),
                ("config_value", models.CharField(max_length=255, verbose_name="配置值")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
            },
        ),
        migrations.CreateModel(
            name="DetectionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("realtime", "实时检测"),
                            ("video", "视频检测"),
                            ("image", "图片检测"),
                        ],
                        max_length=20,
                        verbose_name="检测类型",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/", verbose_name="源文件"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "检测会话",
                "verbose_name_plural": "检测会话",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
                ),
                (
                    "face_detected",
                    models.BooleanField(default=False, verbose_name="检测到面部"),
                ),
                (
                    "smoking_detected",
                    models.BooleanField(default=False, verbose_name="检测到抽烟"),
                ),
                (
                    "phone_detected",
                    models.BooleanField(default=False, verbose_name="检测到打电话"),
                ),
                (
                    "drinking_detected",
                    models.BooleanField(default=False, verbose_name="检测到喝水"),
                ),
                (
                    "eye_aspect_ratio",
                    models.FloatField(blank=True, null=True, verbose_name="眼睛纵横比"),
                ),
                (
                    "yawn_detected",
                    models.BooleanField(default=False, verbose_name="检测到打哈欠"),
                ),
                ("fatigue_level", models.IntegerField(default=0, verbose_name="疲劳等级")),
                (
                    "result_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="results/", verbose_name="结果图像"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_results",
                        to="detection.detectionsession",
                        verbose_name="检测会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "检测结果",
                "verbose_name_plural": "检测结果",
                "ordering": ["-timestamp"],
            },
        ),
    ]
