# Generated by Django 4.2 on 2025-03-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "进行中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                default="in_progress",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
